### ISSUE TITLE
Clear the current location

### ISSUE THREAD

**Issue by albersonn** [Hobbule/ion-google-autocomplete#1]
Is there a way to clear the current location without needing an external action?
Like a 'x' button on the right side of the input.

**Comment by quedicesebas** [comment]
You can clear values and put the button yourself aside the input

**Comment by quedicesebas** [comment]
@albersonn ?

**Comment by albersonn** [comment]
Yeah, that was what I ended up doing.
Sorry for the delay.
Thank you.
